<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="qav-testing" name="edu.vt.qav.tests.grid.RemoteTest" tests="1" failures="1" timestamp="13 Nov 2014 20:22:18 GMT" time="0.002" errors="0">
  <testcase name="GridTest" time="0.002" classname="edu.vt.qav.tests.grid.RemoteTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.testng.internal.PoolService.isFinished(PoolService.java:154)
	at org.testng.internal.PoolService.submitTasksAndWait(PoolService.java:107)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1155)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.TestNG.privateMain(TestNG.java:1301)
	at org.testng.TestNG.main(TestNG.java:1265)
]]>
    </failure>
  </testcase>
</testsuite>
